// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimoneAPI.DbContexts;

#nullable disable

namespace SimoneAPI.Migrations
{
    [DbContext(typeof(SimoneDbContext))]
    partial class SimoneDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("SimoneAPI.DataModels.Attendance", b =>
                {
                    b.Property<Guid>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DancerId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.HasKey("AttendanceId");

                    b.HasIndex("DancerId", "TeamId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("SimoneAPI.DataModels.CalendarDataModel", b =>
                {
                    b.Property<Guid>("CalendarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("AutumnHolidayEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("AutumnHolidayStart")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ChristmasHolidayEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ChristmasHolidayStart")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ChristmasShow")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EasterHolidayEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EasterHolidayStart")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("RecitalShow")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("SummerHolidayEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("SummerHolidayStart")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("WintherHolidayEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("WintherHolidayStart")
                        .HasColumnType("TEXT");

                    b.HasKey("CalendarId");

                    b.ToTable("CalendarDataModels");

                    b.HasData(
                        new
                        {
                            CalendarId = new Guid("00000000-1111-0000-0000-000000000000"),
                            AutumnHolidayEnd = new DateOnly(2024, 10, 21),
                            AutumnHolidayStart = new DateOnly(2024, 10, 17),
                            ChristmasHolidayEnd = new DateOnly(2025, 1, 2),
                            ChristmasHolidayStart = new DateOnly(2024, 12, 23),
                            ChristmasShow = new DateOnly(2024, 12, 10),
                            CreatedDate = new DateTime(2024, 11, 20, 11, 1, 31, 297, DateTimeKind.Utc).AddTicks(3683),
                            EasterHolidayEnd = new DateOnly(2025, 4, 17),
                            EasterHolidayStart = new DateOnly(2025, 4, 10),
                            RecitalShow = new DateOnly(2025, 6, 10),
                            SummerHolidayEnd = new DateOnly(2024, 8, 7),
                            SummerHolidayStart = new DateOnly(2024, 6, 27),
                            WintherHolidayEnd = new DateOnly(2025, 2, 17),
                            WintherHolidayStart = new DateOnly(2025, 2, 13)
                        });
                });

            modelBuilder.Entity("SimoneAPI.DataModels.DancerDataModel", b =>
                {
                    b.Property<Guid>("DancerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("TimeOfBirth")
                        .HasColumnType("TEXT");

                    b.HasKey("DancerId");

                    b.ToTable("DancerDataModels");

                    b.HasData(
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Mathias",
                            TimeOfBirth = new DateOnly(2012, 5, 12)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Emma",
                            TimeOfBirth = new DateOnly(2011, 8, 23)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Name = "Sofie",
                            TimeOfBirth = new DateOnly(2013, 11, 19)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "Lucas",
                            TimeOfBirth = new DateOnly(2012, 3, 15)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Name = "Ida",
                            TimeOfBirth = new DateOnly(2014, 6, 29)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Name = "Oliver",
                            TimeOfBirth = new DateOnly(2010, 4, 20)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Name = "Maja",
                            TimeOfBirth = new DateOnly(2013, 10, 2)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-1000-0000-0000-000000000000"),
                            Name = "Frederik",
                            TimeOfBirth = new DateOnly(2011, 9, 9)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Name = "Marie",
                            TimeOfBirth = new DateOnly(2012, 7, 25)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Name = "Sebastian",
                            TimeOfBirth = new DateOnly(2014, 5, 5)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000012"),
                            Name = "Nora",
                            TimeOfBirth = new DateOnly(2013, 12, 1)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000013"),
                            Name = "Oscar",
                            TimeOfBirth = new DateOnly(2010, 1, 17)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000014"),
                            Name = "Clara",
                            TimeOfBirth = new DateOnly(2012, 2, 6)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000015"),
                            Name = "Magnus",
                            TimeOfBirth = new DateOnly(2011, 8, 30)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000016"),
                            Name = "Signe",
                            TimeOfBirth = new DateOnly(2013, 3, 18)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000017"),
                            Name = "Thea",
                            TimeOfBirth = new DateOnly(2014, 9, 12)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000018"),
                            Name = "Emil",
                            TimeOfBirth = new DateOnly(2010, 5, 14)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000019"),
                            Name = "Freya",
                            TimeOfBirth = new DateOnly(2013, 4, 22)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000020"),
                            Name = "Mikkel",
                            TimeOfBirth = new DateOnly(2012, 11, 8)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000021"),
                            Name = "Liv",
                            TimeOfBirth = new DateOnly(2011, 7, 30)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000022"),
                            Name = "Søren",
                            TimeOfBirth = new DateOnly(2010, 2, 19)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000023"),
                            Name = "Sara",
                            TimeOfBirth = new DateOnly(2013, 6, 4)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000024"),
                            Name = "Joakim",
                            TimeOfBirth = new DateOnly(2012, 3, 26)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000025"),
                            Name = "Tilde",
                            TimeOfBirth = new DateOnly(2014, 10, 30)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000026"),
                            Name = "Mikkel",
                            TimeOfBirth = new DateOnly(2012, 11, 8)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000027"),
                            Name = "Liv",
                            TimeOfBirth = new DateOnly(2011, 7, 30)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000028"),
                            Name = "Søren",
                            TimeOfBirth = new DateOnly(2010, 2, 19)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000029"),
                            Name = "Sara",
                            TimeOfBirth = new DateOnly(2013, 6, 4)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000030"),
                            Name = "Joakim",
                            TimeOfBirth = new DateOnly(2012, 3, 26)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000031"),
                            Name = "Tilde",
                            TimeOfBirth = new DateOnly(2014, 10, 30)
                        });
                });

            modelBuilder.Entity("SimoneAPI.DataModels.Staff", b =>
                {
                    b.Property<Guid>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("TimeOfBirth")
                        .HasColumnType("TEXT");

                    b.HasKey("StaffId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("SimoneAPI.DataModels.TeamDancerRelation", b =>
                {
                    b.Property<Guid>("DancerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTrialLesson")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("LastDanceDate")
                        .HasColumnType("TEXT");

                    b.HasKey("DancerId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamDancerRelations");

                    b.HasData(
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000003"),
                            TeamId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000004"),
                            TeamId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000005"),
                            TeamId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000006"),
                            TeamId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000007"),
                            TeamId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000008"),
                            TeamId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000009"),
                            TeamId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000010"),
                            TeamId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000011"),
                            TeamId = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000012"),
                            TeamId = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000013"),
                            TeamId = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000014"),
                            TeamId = new Guid("44444444-4444-4444-4444-444444444444"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000015"),
                            TeamId = new Guid("44444444-4444-4444-4444-444444444444"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000016"),
                            TeamId = new Guid("44444444-4444-4444-4444-444444444444"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000017"),
                            TeamId = new Guid("55555555-5555-5555-5555-555555555555"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000018"),
                            TeamId = new Guid("55555555-5555-5555-5555-555555555555"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000019"),
                            TeamId = new Guid("55555555-5555-5555-5555-555555555555"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000020"),
                            TeamId = new Guid("66666666-6666-6666-6666-666666666666"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000021"),
                            TeamId = new Guid("66666666-6666-6666-6666-666666666666"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000022"),
                            TeamId = new Guid("66666666-6666-6666-6666-666666666666"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000023"),
                            TeamId = new Guid("77777777-7777-7777-7777-777777777777"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000024"),
                            TeamId = new Guid("77777777-7777-7777-7777-777777777777"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000025"),
                            TeamId = new Guid("77777777-7777-7777-7777-777777777777"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000026"),
                            TeamId = new Guid("88888888-8888-8888-8888-888888888888"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000027"),
                            TeamId = new Guid("88888888-8888-8888-8888-888888888888"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000028"),
                            TeamId = new Guid("88888888-8888-8888-8888-888888888888"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000029"),
                            TeamId = new Guid("99999999-9999-9999-9999-999999999999"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000030"),
                            TeamId = new Guid("99999999-9999-9999-9999-999999999999"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000031"),
                            TeamId = new Guid("99999999-9999-9999-9999-999999999999"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000009"),
                            TeamId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000022"),
                            TeamId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000011"),
                            TeamId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000016"),
                            TeamId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000022"),
                            TeamId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000015"),
                            TeamId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000018"),
                            TeamId = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000017"),
                            TeamId = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000025"),
                            TeamId = new Guid("44444444-4444-4444-4444-444444444444"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000030"),
                            TeamId = new Guid("44444444-4444-4444-4444-444444444444"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000028"),
                            TeamId = new Guid("44444444-4444-4444-4444-444444444444"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000029"),
                            TeamId = new Guid("55555555-5555-5555-5555-555555555555"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000023"),
                            TeamId = new Guid("55555555-5555-5555-5555-555555555555"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000014"),
                            TeamId = new Guid("55555555-5555-5555-5555-555555555555"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000027"),
                            TeamId = new Guid("66666666-6666-6666-6666-666666666666"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000029"),
                            TeamId = new Guid("77777777-7777-7777-7777-777777777777"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000014"),
                            TeamId = new Guid("77777777-7777-7777-7777-777777777777"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000009"),
                            TeamId = new Guid("88888888-8888-8888-8888-888888888888"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000008"),
                            TeamId = new Guid("88888888-8888-8888-8888-888888888888"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000004"),
                            TeamId = new Guid("88888888-8888-8888-8888-888888888888"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000006"),
                            TeamId = new Guid("99999999-9999-9999-9999-999999999999"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000025"),
                            TeamId = new Guid("99999999-9999-9999-9999-999999999999"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        },
                        new
                        {
                            DancerId = new Guid("00000000-0000-0000-0000-000000000018"),
                            TeamId = new Guid("99999999-9999-9999-9999-999999999999"),
                            IsTrialLesson = false,
                            LastDanceDate = new DateOnly(2025, 6, 10)
                        });
                });

            modelBuilder.Entity("SimoneAPI.DataModels.TeamDataModel", b =>
                {
                    b.Property<Guid>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScheduledTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId");

                    b.ToTable("TeamDataModels");

                    b.HasData(
                        new
                        {
                            TeamId = new Guid("11111111-1111-1111-1111-111111111111"),
                            DayOfWeek = 0,
                            Name = "Hiphop1",
                            Number = 1,
                            ScheduledTime = "Mandag 16:00 - 16:45"
                        },
                        new
                        {
                            TeamId = new Guid("22222222-2222-2222-2222-222222222222"),
                            DayOfWeek = 0,
                            Name = "MGP",
                            Number = 2,
                            ScheduledTime = "Tirsdag 15:15 - 16:00"
                        },
                        new
                        {
                            TeamId = new Guid("33333333-3333-3333-3333-333333333333"),
                            DayOfWeek = 0,
                            Name = "Ballet",
                            Number = 3,
                            ScheduledTime = "Onsdag 17:00 - 17:45"
                        },
                        new
                        {
                            TeamId = new Guid("44444444-4444-4444-4444-444444444444"),
                            DayOfWeek = 0,
                            Name = "Hiphop2",
                            Number = 4,
                            ScheduledTime = "Torsdag 16:00 - 16:45"
                        },
                        new
                        {
                            TeamId = new Guid("55555555-5555-5555-5555-555555555555"),
                            DayOfWeek = 0,
                            Name = "Streetdance",
                            Number = 5,
                            ScheduledTime = "Fredag 15:00 - 15:45"
                        },
                        new
                        {
                            TeamId = new Guid("66666666-6666-6666-6666-666666666666"),
                            DayOfWeek = 0,
                            Name = "Argentinsk Tango",
                            Number = 6,
                            ScheduledTime = "Lørdag 11:00 - 11:45"
                        },
                        new
                        {
                            TeamId = new Guid("77777777-7777-7777-7777-777777777777"),
                            DayOfWeek = 0,
                            Name = "Salsa",
                            Number = 7,
                            ScheduledTime = "Mandag 18:00 - 18:45"
                        },
                        new
                        {
                            TeamId = new Guid("88888888-8888-8888-8888-888888888888"),
                            DayOfWeek = 0,
                            Name = "Showdance 1",
                            Number = 8,
                            ScheduledTime = "Tirsdag 17:00 - 17:45"
                        },
                        new
                        {
                            TeamId = new Guid("99999999-9999-9999-9999-999999999999"),
                            DayOfWeek = 0,
                            Name = "Showdance 2",
                            Number = 9,
                            ScheduledTime = "Onsdag 18:00 - 18:45"
                        },
                        new
                        {
                            TeamId = new Guid("07000000-0000-0000-0000-000000000000"),
                            DayOfWeek = 0,
                            Name = "Showdance 3",
                            Number = 10,
                            ScheduledTime = "Torsdag 17:15 - 18:00"
                        });
                });

            modelBuilder.Entity("SimoneAPI.DataModels.WorkingHours", b =>
                {
                    b.Property<Guid>("WorkingHoursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ChosenValueOfWorkingHours")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVikar")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("TEXT");

                    b.HasKey("WorkingHoursId");

                    b.HasIndex("StaffId");

                    b.ToTable("WorkingHours");
                });

            modelBuilder.Entity("SimoneAPI.DataModels.Attendance", b =>
                {
                    b.HasOne("SimoneAPI.DataModels.TeamDancerRelation", "TeamDancerRelation")
                        .WithMany("Attendances")
                        .HasForeignKey("DancerId", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamDancerRelation");
                });

            modelBuilder.Entity("SimoneAPI.DataModels.TeamDancerRelation", b =>
                {
                    b.HasOne("SimoneAPI.DataModels.DancerDataModel", "DancerDataModel")
                        .WithMany("TeamDancerRelations")
                        .HasForeignKey("DancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimoneAPI.DataModels.TeamDataModel", "TeamDataModel")
                        .WithMany("TeamDancerRelations")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DancerDataModel");

                    b.Navigation("TeamDataModel");
                });

            modelBuilder.Entity("SimoneAPI.DataModels.WorkingHours", b =>
                {
                    b.HasOne("SimoneAPI.DataModels.Staff", "Staff")
                        .WithMany("RegisteredWorkingHours")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("SimoneAPI.DataModels.DancerDataModel", b =>
                {
                    b.Navigation("TeamDancerRelations");
                });

            modelBuilder.Entity("SimoneAPI.DataModels.Staff", b =>
                {
                    b.Navigation("RegisteredWorkingHours");
                });

            modelBuilder.Entity("SimoneAPI.DataModels.TeamDancerRelation", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("SimoneAPI.DataModels.TeamDataModel", b =>
                {
                    b.Navigation("TeamDancerRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
